# Generated by Django 5.0.6 on 2024-05-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Arriendos", "0002_region_comuna"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
