# Generated by Django 5.0.6 on 2024-06-09 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arriendos', '0004_alter_comuna_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arriendos.comuna'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
