# Generated by Django 5.0.6 on 2024-06-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arriendos', '0005_alter_propiedad_comuna_alter_propiedad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='precio_mensual',
            field=models.IntegerField(),
        ),
    ]
